### ISSUE TITLE
Volunteer Calendar.

### ISSUE THREAD

**Issue by talgarusi** [talgarusi/Itorerut-Project#10]
# Feature:
Volunteer Calendar.
# User story:
The system will have a calendar that will contain all the movement's activities.
There will be events that built in the calendar (such as: movement events, team meeting) the only people who may change the major events will be those with the permissions.
All the volunteers could see the calendar and will be able to update it for their own purposes, but they cannot overwrite a major event.
In terms of permissions the "stability" of the events will be set by the user rank. E.g. The team manager will set the team meeting and the volunteer won't be able to re-schedule it or re-write it.
# Bugs:

**Comment by moshena** [comment]
Done
