### ISSUE TITLE
VMS Tasks

### ISSUE THREAD

**Issue by talgarusi** [talgarusi/Itorerut-Project#11]
# Feature:
VMS Tasks
# User story:
The system will be able to create/ read/ update/ delete tasks.
Fields:
- [ ] Project.
2) Details.
3) Due date.
4) Assigning person.
5) Priority.
6) done?

Every volunteer has a task list which includes sub lists, one for each project he participates.
Permissions: Every volunteer has a task list which includes sub lists, one for each project he participates.
Every volunteer is permitted to add/ read/update/create tasks. The volunteer's manager is also permitted to add for his subjects.
# Bugs:

**Comment by shon-otmazgin** [comment]
Done during iteration 2, the customer asked to share the tasks with all the movement members without different Permissions, the motivation for that is to push each other to take tasks and help others.
