### ISSUE TITLE
console error

### ISSUE THREAD

**Issue by shon-otmazgin** [talgarusi/Itorerut-Project#21]
glyphicons-halflings-regular.woff
glyphicons-halflings-regular.woff2

**Comment by ItamarShDev** [comment]
please be clearer in your issue details.
you have a problem with web fonts?

**Comment by shon-otmazgin** [comment]
yes , we are using those fonts, we are getting from the console 404 not found on those font, despite the fact that they actually loaded.
Its a familiar problem with those fonts, need to find a solution.

**Comment by shon-otmazgin** [comment]
Solved :+1: 

Need to add web.config file to the root folder with the content 
```xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
    <system.webServer>
        <staticContent>
            <remove fileExtension=".woff" />
			<remove fileExtension=".woff2" />
			<mimeMap fileExtension=".woff" mimeType="application/font-woff" />
			<mimeMap fileExtension=".woff2" mimeType="application/font-woff" />
        </staticContent>
    </system.webServer>
</configuration>
```
