### ISSUE TITLE
Empty name for list

### ISSUE THREAD

**Issue by shon-otmazgin** [talgarusi/Itorerut-Project#23]
when entering an empty name to a list there is a overlap in the sidebar
![image](https://cloud.githubusercontent.com/assets/17564565/14493807/354f4832-0190-11e6-8678-b82401e2b7a2.png)

**Comment by moshena** [comment]
i see that it impossible to entering an empty name for list.
it`s solve it?

**Comment by shon-otmazgin** [comment]
@moshena still not, the problem invoke after using with Bootstrap Modals, maybe need to think of other solution.

**Comment by shon-otmazgin** [comment]
bug fixed.
the modal validate if the name is an empty string and if so, he **not** invoke the newList() function.
