### ISSUE TITLE
from local storage to mongoDB

### ISSUE THREAD

**Issue by shon-otmazgin** [talgarusi/Itorerut-Project#24]
need to integrate the volunteer data base with mongoDB

**Comment by moshena** [comment]
i open account in mLab. now i think we should change the struct of the files.
we need the directory "bin" for azure server.
explanation:
[link to the tirgul](https://github.com/jce-il/se-class/blob/master/tirgul/Node%20and%20azure.pdf)
i want to open a new branch and to handle this there.
someone agree with me?

**Comment by shon-otmazgin** [comment]
I think that we can to integrate with Mongo DB localy so we could test the environment. 
And later.. we only need to change the mongo URL from localhist:27017 to moab address.

We can do it on yours branch or the master also good...

**Comment by shon-otmazgin** [comment]
update
we are using mLab solution for integrate with mongoDB.

we started to integrate each iteration features to the DB.

**Comment by shon-otmazgin** [comment]
@moshena functionality were added fro all the iterations so far.
MongoDB using Mlab
