### ISSUE TITLE
Add counter for numbers of task

### ISSUE THREAD

**Issue by GalZaken** [talgarusi/Itorerut-Project#27]

**Comment by shon-otmazgin** [comment]
@GalZaken describe the details of the issue in the body

**Comment by talgarusi** [comment]
@shon-otmazgin  he meant that we need to add counter in the calendar page for every task that someone is adding so the organization would be able to track on how many open tasks and event they have in the system.

**Comment by shon-otmazgin** [comment]
@GalZaken no need counter.
you can ask the list collection from the DB and ask for the return object length
