### ISSUE TITLE
the new css file is not attached to calendar controller  

### ISSUE THREAD

**Issue by talgarusi** [talgarusi/Itorerut-Project#29]

**Comment by moshena** [comment]
check it right now.

**Comment by moshena** [comment]
try now. i fixed the link in the layout.ejs
from         <link href="css/custom/calendadr-style.css" rel="stylesheet"  type="text/css">
to             <link href="css/custom/calendar-style.css" rel="stylesheet"  type="text/css">
i think it will solve it
