### ISSUE TITLE
calendar design problem @talgarusi

### ISSUE THREAD

**Issue by moshena** [talgarusi/Itorerut-Project#30]
when you in the page of the calendar the number of elements in row should be 7 like number of days in week.
when you zoom in or zoom out it change from 7 elements in row to more or less.

**Comment by shon-otmazgin** [comment]
@moshena @talgarusi do the zoom feature is necessary ?

**Comment by talgarusi** [comment]
no we need do make the size of the days element fixed for every Resolution and for different screens.

**Comment by shon-otmazgin** [comment]
i think Bootstarp3 is good solution ? do you ?

[this repository is using Bootstarp3 ](https://github.com/Serhioromano/bootstrap-calendar)

**Comment by moshena** [comment]
@shon-otmazgin i tried to run this example but somehow the calendar didn`t apear?
it`s work on your pc?
(i clone it and than i run)

**Comment by shon-otmazgin** [comment]
try this [link](http://bootstrap-calendar.azurewebsites.net/) it running on AZURE

**Comment by moshena** [comment]
@shon-otmazgin yes it`s work good.
we need to divide the screen by Bootstarp or to print the all calendar with this?

**Comment by shon-otmazgin** [comment]
i guess divide the screen with Bootstarp

**Comment by moshena** [comment]
o.k. i will check it

2016-05-09 15:39 GMT+03:00 Shon Otmazgin <notifications@github.com>:

**Comment by moshena** [comment]
me and @talgarusi solve this.
you can see in the calendar branch the new design.

**Comment by shon-otmazgin** [comment]
Share it...
