### ISSUE TITLE
server side - problem with HTTP request

### ISSUE THREAD

**Issue by moshena** [talgarusi/Itorerut-Project#33]
I have some problem on the routing in the server side.
This is began when i add a two  HTTP methods in the server side for the DB.
The problem is that if you go to our URL and than you will click on Calendar this windows will show up:
![](https://github.com/talgarusi/Itorerut-Project/blob/master/images/Iteretion%202%20images/http_issue_pic2.png?raw=true)

But if you put on the address URL\calnedar this page will show up:
![](https://github.com/talgarusi/Itorerut-Project/blob/master/images/Iteretion%202%20images/http_Issue_pic1.png?raw=true)

This output come from the HTTP request in the server side:
![](https://github.com/talgarusi/Itorerut-Project/blob/master/images/Iteretion%202%20images/http_Issue_pic5.png?raw=true)

The same problem happen in the "contacts"  that uses the same functions like the calendar

**Comment by shon-otmazgin** [comment]
your slash is wrong .... 
any way be aware that the DB methods need write before the follwing 3 l;ine in the server side 
```javascript
app.get('/', routes.index); 
app.get('/partials/:name', routes.partials);
app.get('*', routes.index);
```

**Comment by moshena** [comment]
we solve it.

the solution is to change the route of the "get" method to "calendarDB"
![](https://raw.githubusercontent.com/talgarusi/Itorerut-Project/master/images/Iteretion%202%20images/http_Issue_pic6.png)
