### ISSUE TITLE
website logo update 

### ISSUE THREAD

**Issue by ofirnagadi** [talgarusi/Itorerut-Project#35]
From movement desiner.

**Comment by ofirnagadi** [comment]
I received the logo css, and now i need to ajust it to our css.

**Comment by ofirnagadi** [comment]
I have added the logo,
what is your oppinion? @shon-otmazgin 
![](https://github.com/talgarusi/Itorerut-Project/blob/master/images/Logo-added1.png?raw=true)

![](https://github.com/talgarusi/Itorerut-Project/blob/master/public/images/movment-logo.png?raw=true)

**Comment by shon-otmazgin** [comment]
looks good... 
@moshena @talgarusi @GalZaken have you agree ?
