### ISSUE TITLE
icons problem

### ISSUE THREAD

**Issue by ofirnagadi** [talgarusi/Itorerut-Project#40]
ionicons - cannot laod the icons foler correctly.

**Comment by ofirnagadi** [comment]
Errors record:
Failed to decode downloaded font: http://localhost:3000/css/fonts/ionicons.ttf?v=2.0.0
localhost/:1 OTS parsing error: invalid version tag
localhost/:1 Failed to decode downloaded font: http://localhost:3000/css/fonts/ionicons.ttf?v=2.0.0
localhost/:1 OTS parsing error: invalid version tag
localhost/:1 Failed to decode downloaded font: http://localhost:3000/css/fonts/ionicons.woff?v=2.0.0
localhost/:1 OTS parsing error: invalid version tag
localhost/:1 Failed to decode downloaded font: http://localhost:3000/css/fonts/ionicons.woff?v=2.0.0
localhost/:1 OTS parsing error: invalid version tag

**Comment by GalZaken** [comment]
@ofirnagadi Please be aware that the CSS files and the fonts file should be the same version.
You can download the latest version of [ionicon 2.0.1](https://github.com/driftyco/ionicons/archive/v2.0.1.zip) and update the files in the repository.

**Comment by ofirnagadi** [comment]
O.K - tried it,
it works perfect  :+1:
