### ISSUE TITLE
dashboard graph need to be created.

### ISSUE THREAD

**Issue by ofirnagadi** [talgarusi/Itorerut-Project#41]
the section is ready, and needs to created on angular.

**Comment by ofirnagadi** [comment]
@shon-otmazgin  @GalZaken 
grapg as craeted and added,

please give me your reviews.
![image](https://github.com/talgarusi/Itorerut-Project/blob/master/images/Iteretion%204%20images/graph.png?raw=true)

**Comment by shon-otmazgin** [comment]
WOW looks fancy !
@ofirnagadi  can you share your code ??

**Comment by ofirnagadi** [comment]
Hi,
you can find the code under the remark "// FUNCTIONS FOR GRAPH:"
and the main function is "function drawStuff()".
