### ISSUE TITLE
Create statistics functionality for the dashboard boxes

### ISSUE THREAD

**Issue by GalZaken** [talgarusi/Itorerut-Project#42]
Adding functionality for each box accordingly.
![image](https://github.com/talgarusi/Itorerut-Project/blob/master/images/Iteretion%204%20images/DashboardBoxes.png?raw=true)

**Comment by GalZaken** [comment]
@ofirnagadi I added the functionality for the "Tasks Statistics" box, it works fine.

**Comment by shon-otmazgin** [comment]
It seems you hve a problem...
Enter the [website]( http://vms-project1.azurewebsites.net)
   it write that we have 20 volunteers but actully we have 11

**Comment by GalZaken** [comment]
@shon-otmazgin ofir is taking care this functionality,
20 volunteers it's just an example of the box design.

**Comment by ofirnagadi** [comment]
The functionality to the event and the volunteers boxes as added.
@GalZaken

**Comment by shon-otmazgin** [comment]
@ofirnagadi @GalZaken  try to save only 2 digits after the .

![image](http://i63.tinypic.com/2cp52z5.png)

**Comment by GalZaken** [comment]
@shon-otmazgin I opened [issue](https://github.com/talgarusi/Itorerut-Project/issues/45) for this bug,
thanks.

**Comment by ofirnagadi** [comment]
We can pipe the output/resualt to show less digits.

**Comment by GalZaken** [comment]
Problem Fixed ([issue](https://github.com/talgarusi/Itorerut-Project/issues/45)).
@ofirnagadi  @shon-otmazgin
