### ISSUE TITLE
Create the dashboard event list

### ISSUE THREAD

**Issue by GalZaken** [talgarusi/Itorerut-Project#43]
Create the dashboard calendar section and adding functionality.
@ofirnagadi @talgarusi @moshena

**Comment by ofirnagadi** [comment]
Future event section as added.
![](https://github.com/talgarusi/Itorerut-Project/blob/master/images/Iteretion%204%20images/Fixed%20Events.png?raw=true)

**Comment by shon-otmazgin** [comment]
@GalZaken @ofirnagadi 
check out this style...
http://bootsnipp.com/snippets/featured/event-list
