### ISSUE TITLE
Create dashboard TODO

### ISSUE THREAD

**Issue by GalZaken** [talgarusi/Itorerut-Project#44]
Create the dashboard TODO List. @ofirnagadi

**Comment by GalZaken** [comment]
Added the feature with the top 4 lists which have more than 33.33% tasks to do.

**Comment by GalZaken** [comment]
@ofirnagadi @shon-otmazgin I add a progress bar for each task in the dashboard ToDo lists.
What do you say about it?
![image](https://github.com/talgarusi/Itorerut-Project/blob/master/images/Iteretion%204%20images/TODO-Lists-PB.png?raw=true)

**Comment by GalZaken** [comment]
@shon-otmazgin @ofirnagadi Edit of the Dashboard ToDo lists:
![image](https://github.com/talgarusi/Itorerut-Project/blob/master/images/Iteretion%204%20images/TODO-Lists-PB2.png?raw=true)

**Comment by shon-otmazgin** [comment]
Looks good ..

**Comment by GalZaken** [comment]
Thank you!
