### ISSUE TITLE
Tasks Statistics box - percent problem 

### ISSUE THREAD

**Issue by GalZaken** [talgarusi/Itorerut-Project#45]
Tasks Statistics result should be fixed for 2 numbers after the point.
@shon-otmazgin

**Comment by shon-otmazgin** [comment]
@ofirnagadi it's your scope...

![image](http://i63.tinypic.com/205tdtk.png)

**Comment by shon-otmazgin** [comment]
Can you share us the fixing code ??
@galZaken

**Comment by GalZaken** [comment]
Bug fixed.
![image](https://github.com/talgarusi/Itorerut-Project/blob/master/images/Iteretion%204%20images/TasksStatisticsPercentBugFIXED.png?raw=true)
This is the update of the tasks statistics function code:
```
// FUNCTIONS FOR TASK STATISTICS BOX:
        $scope.tasksStatistics = function(https://github.com/talgarusi/Itorerut-Project/blob/master/images/Iteretion%204%20images/TasksStatisticsPercentBugFIXED.png?raw=true) {

            var completedTasksCounter = 0;
            var listIsComplete = function(list) {

                for (var i=0; i<list.tasks.length; i++)
                    if (!list.tasks[i].status)
                        return false;
                return true;
            };

            for (var i=0; i<$scope.lists.length; i++) {

                if (listIsComplete($scope.lists[i]))
                    completedTasksCounter++;
            }

            return (completedTasksCounter/$scope.lists.length*100).toFixed(2);
        };

**Comment by shon-otmazgin** [comment]
Easy life with JS :-1

**Comment by GalZaken** [comment]
@shon-otmazgin the lists array could be empty?
maybe we should add condition to check it because it may cause a bug in this code line:
```
return (completedTasksCounter/$scope.lists.length*100).toFixed(2);

**Comment by shon-otmazgin** [comment]
You right..it will throw divide by zero exception.

Also remove the 2 digit after the point is the number is integer.

**Comment by GalZaken** [comment]
@shon-otmazgin I added a zero condition and fixed the display of the statistical results in percentages.
I added this code lines to fix that:
```
            var statsResult = completedTasksCounter/$scope.lists.length*100;
            if (statsResult % 1 === 0) // statistics result is Integer:
                return statsResult;
            else
                return statsResult.toFixed(2);
```
Screenshots:
![image](https://github.com/talgarusi/Itorerut-Project/blob/master/images/Iteretion%204%20images/TasksStatisticsPercentBugFIXED-2.png?raw=true)
