### ISSUE TITLE
Edit graph fanctionality

### ISSUE THREAD

**Issue by ofirnagadi** [talgarusi/Itorerut-Project#49]
fanctionality to real danta is needed.

**Comment by GalZaken** [comment]
@ofirnagadi I ad the real date and fixed the graph percents problem.

**Comment by GalZaken** [comment]
@ofirnagadi Graph functionality changed but we have problem with the data.

**Comment by shon-otmazgin** [comment]
@ofirnagadi @GalZaken 
the setOnLoad function need to be called right after you got the list from the DB
i just relocate the callback to the http request

```
 $http.get("/listsDB").
    then(function(response) {
        $scope.lists = response.data;
        google.charts.setOnLoadCallback(drawStuff);
    }, 
        function(response) {
            console.log("Error retrieving lists.");
            
    });
```

**Comment by GalZaken** [comment]
Thanks @shon-otmazgin  it works great now!
