### ISSUE TITLE
Project - Iteration 4 - Submission.

### ISSUE THREAD

**Issue by GalZaken** [talgarusi/Itorerut-Project#52]
#### Iteration Page: [Link](https://github.com/talgarusi/Itorerut-Project/wiki/Iteration-4---Dashboard)
- [x] Feature scenarios/tests passing
- [x] Iteration page updated, including:
  - [x] Iteration retrospective
  - [x] Client review
  - [x] Issues updates
  - [x] Section on application of course materials
- [x] git tag
- [x] Next iteration: Final Iteration.
- [x] All engineers filled peer-review 
- [x] Submitted
  - [x] Announcement in chat room
  - [x] Assign this issue to checker
  - [x] Register for a review meeting

**Comment by shon-otmazgin** [comment]
@ItamarShDev final project summary were uploaded to the iteration 4 wiki.

also here is a [link](https://github.com/talgarusi/Itorerut-Project/blob/master/Project-Summary/project%20summary.docx?raw=true)

**Comment by robi-y** [comment]
Interesting

**Comment by ItamarShDev** [comment]
:+1:
