### ISSUE TITLE
VMS Volunteer

### ISSUE THREAD

**Issue by talgarusi** [talgarusi/Itorerut-Project#6]
# Feature:
VMS Volunteer.
# User story:
The system will be able to create/ read/ update volunteers.
The data base will save the following fields:
1) Email.
2) First-Name.
3) Last-Name.
4) Phone-Numbers.
5) Address -Neighborhood
6) Age.
7) Birthday.
8) Anniversary day.
9) Relationship status.
10) Qualifications.
11) Join-Date.
12) Comments.
13) Participate in teams.
14) Status.
16) Role
Permissions: Human Resource Management..
# Bugs:

**Comment by shon-otmazgin** [comment]
done
