### ISSUE TITLE
Alert for shortage of volunteers.

### ISSUE THREAD

**Issue by talgarusi** [talgarusi/Itorerut-Project#8]
# Feature:
Alert for shortage of volunteers.
# User story:
As a part of the continuous and proper activity of movement and its management and resource planning , In order to abstain shortage in volunteers, the system will alert management and resource planning team when the number of volunteers will reach a predetermined point.
# Bugs:

**Comment by moshena** [comment]
not needed

**Comment by shon-otmazgin** [comment]
Agree, it out of our scope.
