### ISSUE TITLE
VMS Events

### ISSUE THREAD

**Issue by talgarusi** [talgarusi/Itorerut-Project#9]
# Feature:
VMS Events
# User story:
The system will be able to create / read / update / delete events
Fields:
1) Location.
2) time.
3) Participants.
4) Details.
5) Event Creator.
Permissions: Every volunteer in the movement is permitted to create / read / update / delete events.
# Bugs:

**Comment by moshena** [comment]
we propertis the event object by this attributes:
1) Location.
2) time.
3) Participants.
4) Details.
5) Event Creator.
